"""
strategy_codegen.py — a strategy spec becomes a standalone Python file master can read and run.

Master asked for the strategy "converting to code mostly Python to execute". See spec Section 103 for
the decisions; the two that shape this file:

RĀMA DOES NOT EXECUTE WHAT IT GENERATES. The backtest master judges is run by the audited interpreter
in `strategy_spec.py`. This file produces an artefact. Two reasons: `exec`-ing generated source inside
the process that holds master's data is arbitrary code execution, and — the one that actually matters —
if the emitted code were the thing that ran the backtest, a codegen bug would silently change the
number master is deciding on. Separating them lets the two be compared.

THE EMITTED CODE IS THE INTERPRETER'S OWN SOURCE, NOT A TEMPLATE. Every helper and signal function is
copied out with `inspect.getsource()` from the module the backtest used. Agreement is therefore
structural: there is no second implementation to drift. A template string would go stale the first time
a block was fixed in one place and not the other, and it would go stale silently.

NO ORDER PLACEMENT. The script prints signals. Section 95 locked this and it is not a v1 limitation to
be lifted later — StockMind does not place trades.
"""

from __future__ import annotations

import datetime as _dt
import inspect
import json
from typing import Optional

# RELATIVE FIRST, ABSOLUTE AS A FALLBACK. `engine/__init__` imports the dispatcher, which imports
# numpy, so `from engine import strategy_codegen` drags the whole ML stack in — and this module and the
# one it depends on are deliberately stdlib-only so they can be tested on a machine without it (the
# same reasoning as Section 64's lazy imports). The fallback lets a caller put `engine/` on the path and
# import these two alone.
try:
    from . import strategy_spec as S
except ImportError:                                  # pragma: no cover - exercised by the suite
    import strategy_spec as S

# The helpers every emitted script needs, in dependency order. Listed rather than discovered so the
# output is deterministic and reviewable — a generated file master is asked to trust must be the same
# file every time for the same spec.
_HELPERS = [
    S._sma, S._ema, S._stdev, S._rsi, S._atr, S._rolling_max, S._rolling_min,
    S._swing_points, S._last_n_confirmed, S._linfit_slope,
    # Sizing is copied too, rather than re-written in the runner template. It decides how much money
    # is at risk, so a second implementation of it is the last place drift should be tolerated.
    S.position_size,
]

_HEADER = '''#!/usr/bin/env python3
"""
{name}

GENERATED BY RAMA - StockMind strategy compiler (spec Section 103).
Do not edit this file to change the strategy; edit the strategy and regenerate, or the record of what
was tested stops matching what runs.

  instrument   {symbol} ({exchange}), {interval} bars
  side         {side}
  entry        {combiner}
  exit         {exitline}
  sizing       {capital:,.0f} capital, {risk}% risked per trade
  costs        {costs}% assumed round trip
  spec hash    {spec_hash}
  generated    {generated}
  variants     {trials} searched{verdictline}

THIS SCRIPT PRINTS SIGNALS. IT DOES NOT PLACE ORDERS, and Rama will not be given that ability.

The emitted file is deliberately ASCII-only. `main` prints this docstring when run with no arguments,
and a Windows console defaults to cp1252 - a macron in here would make the generated script crash on
the most basic thing master could do with it.

The block logic below is copied verbatim from the engine functions that produced the backtest, so this
file and that backtest cannot disagree.

Usage:
    python {filename} bars.csv

    bars.csv needs a header row with: date,open,high,low,close,volume
    The same file the engine stores under <userData>/stockmind/history works unchanged.
"""

import csv
import json
import math
import sys

# PARSED, NOT PASTED AS A LITERAL. This was `SPEC = {{...}}` with the JSON written straight into the
# file, which is valid Python only while the spec contains no booleans and no nulls. It contains both:
# `stopPct` is `null` for a target-only strategy, and Section 115 added `instrumentDerived`. So EVERY
# generated script for a strategy without a stop was already a NameError on `null` and nobody had run
# one. Kept as readable JSON because that is what a human wants to read; parsed at runtime because that
# is what Python needs. `"""` cannot appear inside JSON - a quote is escaped as \\" - so the raw string
# cannot be terminated early.
SPEC = json.loads(r"""{spec_json}""")

'''

_RUNNER = '''

# ── The combiner and the walk, copied from the engine ────────────────────────

_SIGNALS = {
    "sma_cross": _sig_sma_cross,
    "ema_cross": _sig_ema_cross,
    "price_vs_sma": _sig_price_vs_sma,
    "rsi_band": _sig_rsi_band,
    "macd_cross": _sig_macd_cross,
    "bollinger_touch": _sig_bollinger_touch,
    "atr_expansion": _sig_atr_expansion,
    "breakout": _sig_breakout,
    "volume_surge": _sig_volume_surge,
    "higher_structure": _sig_higher_structure,
    "lower_structure": _sig_lower_structure,
    "trendline_break": _sig_trendline_break,
    "day_of_week": _sig_day_of_week,
    "time_of_day": _sig_time_of_day,
}


def entry_signals(spec, bars):
    blocks = spec["entry"]["blocks"]
    op = spec["entry"]["op"]
    k = int(spec["entry"].get("k") or 1)
    if not blocks or not bars:
        return [False] * len(bars)
    arrays = [_SIGNALS[nb["id"]](bars, nb["params"]) for nb in blocks]
    out = [False] * len(bars)
    for i in range(len(bars)):
        hits = sum(1 for a in arrays if a[i])
        if op == "all":
            out[i] = hits == len(arrays)
        elif op == "any":
            out[i] = hits > 0
        else:
            out[i] = hits >= k
    return out


def simulate(spec, bars):
    """
    One position at a time. Entry on the NEXT bar's open, because a signal from a bar's close cannot
    be acted on at that close. A stop and a target touched in the same bar resolve as the STOP — bar
    data cannot say which came first, and the optimistic reading manufactures winners in exactly the
    volatile bars where it matters most.
    """
    n = len(bars)
    sig = entry_signals(spec, bars)
    long_side = spec["side"] == "long"
    stop_pct = spec["exit"]["stopPct"]
    target_pct = spec["exit"]["targetPct"]
    max_bars = int(spec["exit"].get("maxBars") or 0)

    trades = []
    i = 1
    while i < n:
        if not sig[i - 1]:
            i += 1
            continue
        entry_price = float(bars[i]["open"])
        if entry_price <= 0:
            i += 1
            continue
        stop_price = (entry_price * (1 - stop_pct / 100.0) if long_side
                      else entry_price * (1 + stop_pct / 100.0)) if stop_pct else None
        target_price = (entry_price * (1 + target_pct / 100.0) if long_side
                        else entry_price * (1 - target_pct / 100.0)) if target_pct else None
        exit_idx = exit_price = why = None
        j = i
        while j < n:
            hi = float(bars[j]["high"])
            lo = float(bars[j]["low"])
            hit_stop = stop_price is not None and (lo <= stop_price if long_side else hi >= stop_price)
            hit_target = (target_price is not None
                          and (hi >= target_price if long_side else lo <= target_price))
            if hit_stop:
                exit_idx, exit_price, why = j, stop_price, "stop"
                break
            if hit_target:
                exit_idx, exit_price, why = j, target_price, "target"
                break
            if max_bars and (j - i + 1) >= max_bars:
                exit_idx, exit_price, why = j, float(bars[j]["close"]), "time"
                break
            j += 1
        if exit_idx is None:
            break
        gross = ((exit_price - entry_price) / entry_price * 100.0 if long_side
                 else (entry_price - exit_price) / entry_price * 100.0)
        trades.append({
            "entryIndex": i, "exitIndex": exit_idx,
            "entryDate": str(bars[i].get("date") or ""),
            "exitDate": str(bars[exit_idx].get("date") or ""),
            "entryPrice": entry_price, "exitPrice": exit_price,
            "bars": exit_idx - i + 1, "grossPct": gross, "exitReason": why,
        })
        i = exit_idx + 1
    return trades


def load_bars(path):
    bars = []
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            try:
                bars.append({
                    "date": row["date"],
                    "open": float(row["open"]), "high": float(row["high"]),
                    "low": float(row["low"]), "close": float(row["close"]),
                    "volume": float(row.get("volume") or 0.0),
                })
            except (KeyError, TypeError, ValueError):
                continue                      # a malformed row is skipped, not fatal
    return bars


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    bars = load_bars(argv[1])
    if len(bars) < 30:
        print(f"only {len(bars)} usable bars in {argv[1]} — too few to judge anything")
        return 1

    trades = simulate(SPEC, bars)
    costs = SPEC["costs"]
    round_trip = 2.0 * (costs["commissionPct"] + costs["slippagePct"]) + costs["spreadPct"]

    print(f"{SPEC['name']} — {SPEC['symbol']} {SPEC['interval']} {SPEC['side']}")
    print(f"{len(bars)} bars, {bars[0]['date']} to {bars[-1]['date']}")
    print(f"{len(trades)} round trips, {round_trip:.2f}% assumed round-trip cost\\n")

    if not trades:
        print("no trades — the entry conditions never met on this data")
        return 0

    nets = [t["grossPct"] - round_trip for t in trades]
    wins = sum(1 for r in nets if r > 0)
    equity = 100.0
    peak = 100.0
    worst_dd = 0.0
    for r in nets:
        equity *= (1.0 + r / 100.0)
        peak = max(peak, equity)
        worst_dd = max(worst_dd, (peak - equity) / peak)

    print(f"{'entry':<20} {'exit':<20} {'bars':>5} {'gross%':>9} {'net%':>9} {'units':>7}  why")
    for t in trades[-20:]:
        print(f"{t['entryDate'][:19]:<20} {t['exitDate'][:19]:<20} {t['bars']:>5} "
              f"{t['grossPct']:>9.2f} {t['grossPct'] - round_trip:>9.2f} "
              f"{position_size(SPEC, t['entryPrice']):>7} {t['exitReason']}")
    if len(trades) > 20:
        print(f"... {len(trades) - 20} earlier trades not shown")

    print(f"\\nwin rate      {wins / len(trades) * 100:.1f}%  ({wins} of {len(trades)})")
    print(f"expectancy    {sum(nets) / len(nets):+.2f}% net per trade")
    print(f"total return  {equity - 100.0:+.1f}% compounded, {len(trades)} trades")
    print(f"max drawdown  {worst_dd * 100:.1f}%")
    print(f"\\nThese are the realised numbers on this file. They are NOT a forecast, and a win rate")
    print(f"from a backtest is not a forward-looking probability. {SPEC['_trials']} variants were")
    print(f"searched to arrive at this configuration; the more that were tried, the higher the bar a")
    print(f"result must clear to mean anything. Rama's verdict on that is in the strategy panel.")
    print(f"\\nNo orders are placed by this script.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
'''


def _needed_signal_functions(spec: dict) -> list:
    """
    Every `_sig_*` the emitted script needs.

    ALL of them, not only those in this spec. The dispatch table in the runner names them all, so
    emitting a subset would produce a file with a NameError the moment master edited the spec dict at
    the top — and editing that dict is the obvious thing to try.
    """
    out = []
    for bid in sorted(S.BLOCKS):
        fn = S.BLOCKS[bid]["fn"]
        if fn is not None:
            out.append(fn)
    return out


def _exit_line(spec: dict) -> str:
    parts = []
    if spec["exit"].get("stopPct"):
        parts.append(f"stop {spec['exit']['stopPct']}%")
    if spec["exit"].get("targetPct"):
        parts.append(f"target {spec['exit']['targetPct']}%")
    if spec["exit"].get("maxBars"):
        parts.append(f"{spec['exit']['maxBars']} bars max")
    return ", ".join(parts) or "none"


def _combiner_line(spec: dict) -> str:
    op = spec["entry"]["op"]
    names = [S.BLOCKS[b["id"]]["label"] for b in spec["entry"]["blocks"]]
    if op == "all":
        return " AND ".join(names) or "nothing"
    if op == "any":
        return " OR ".join(names) or "nothing"
    return f"at least {spec['entry'].get('k', 1)} of: " + ", ".join(names)


def to_python(spec: dict, *, verdict: Optional[dict] = None, trials: int = 1,
              filename: str = "strategy.py") -> dict:
    """
    Emit the standalone script for a validated spec.

    @returns `{ok, code, filename, specHash, lines, reason}`

    THE VERDICT TRAVELS WITH THE CODE. A generated strategy file that does not carry what Rāma
    concluded about it is the most dangerous artefact this feature could produce: it would look like an
    endorsement, get kept, and be run months later with no record of whether the backtest ever passed.
    So the header states the verdict, or states that there was not one.
    """
    v = S.validate_spec(spec)
    if not v["ok"]:
        return {"ok": False, "reason": "; ".join(v["errors"]), "code": None}

    clean = v["spec"]
    costs = clean["costs"]
    round_trip = 2.0 * (costs["commissionPct"] + costs["slippagePct"]) + costs["spreadPct"]

    if verdict is None:
        verdictline = ("\n  verdict      NOT BACKTESTED - nothing here has been judged. Do not trade "
                       "this on the strength of the code existing.")
    else:
        passed = bool(verdict.get("passed"))
        verdictline = (f"\n  verdict      {'PASSED' if passed else 'DID NOT PASS'} - "
                       f"{verdict.get('reason', 'no reason recorded')}")
        if not passed:
            verdictline += ("\n               Rama does not consider this a demonstrated edge. The "
                            "code is here so it can be inspected and improved, not because it works.")
    if v["blocked"]:
        verdictline += ("\n  note         contains blocks that cannot be backtested: "
                        + ", ".join(b["label"] for b in v["blocked"]))

    embedded = dict(clean)
    embedded["_trials"] = int(trials)

    header = _HEADER.format(
        name=clean["name"],
        symbol=clean["symbol"], exchange=clean["exchange"], interval=clean["interval"],
        side=clean["side"].upper(),
        combiner=_combiner_line(clean),
        exitline=_exit_line(clean),
        capital=clean["sizing"]["capital"], risk=clean["sizing"]["riskPct"],
        costs=f"{round_trip:.2f}",
        spec_hash=v["specHash"],
        generated=_dt.datetime.now().isoformat(timespec="seconds"),
        trials=int(trials),
        verdictline=verdictline,
        filename=filename,
        spec_json=json.dumps(embedded, indent=4, sort_keys=True),
    )

    body_parts = [inspect.getsource(fn) for fn in _HELPERS]
    body_parts.append("\n# ── Block logic, copied from the engine that ran the backtest ─────────────\n")
    body_parts.extend(inspect.getsource(fn) for fn in _needed_signal_functions(clean))

    code = header + "\n# ── Series helpers ───────────────────────────────────────────────────────\n\n" \
        + "\n\n".join(p.rstrip() for p in body_parts) + _RUNNER
    return {
        "ok": True, "code": code, "filename": filename,
        "specHash": v["specHash"], "lines": code.count("\n") + 1,
        "blocked": v["blocked"],
    }
