'use strict';

/**
 * beforeBuild.cjs — Pre-build hook for electron-builder.
 *
 * Runs before packaging:
 *   1. Rebuild native modules (argon2, node-pty) for the target Electron version
 *   2. Verify icon files exist
 *   3. Generate placeholder icons if missing (dev builds only)
 */

const { execSync }   = require('child_process');
const { existsSync, writeFileSync, mkdirSync } = require('fs');
const path           = require('path');

/**
 * electron-builder's `beforeBuild` hook (unlike `afterPack`) is called BEFORE
 * app.asar exists and receives { appDir, electronVersion, platform, arch } —
 * not { appOutDir, packager }. There is no `packager` object at this point, so
 * `context.packager.projectDir` always threw here. `appDir` is the project
 * root (same thing `packager.projectDir` would have resolved to), so use that.
 * See https://www.electron.build/docs/api/app-builder-lib.Interface.Hooks
 *
 * Returning `false` tells electron-builder "dependency install/rebuild is
 * handled outside of electron-builder" so it does not also try to run its own
 * npmRebuild pass on top of this hook (see packager.js installAppDependencies).
 */
module.exports = async function(context) {
  const { appDir, platform } = context;
  const root = appDir;

  console.log('\n⬢ Rāma AGI — Pre-build checks...\n');

  // ── Check icon files ────────────────────────────────────────────────────────
  const assetsDir = path.join(root, 'assets');
  mkdirSync(assetsDir, { recursive: true });

  // If source logo exists but icons haven't been generated yet, generate them
  const sourceLogo = path.join(assetsDir, 'logo-source.png');
  const iconPng    = path.join(assetsDir, 'icon.png');
  if (existsSync(sourceLogo) && !existsSync(iconPng)) {
    console.log('  ⬢ logo-source.png found — auto-generating icons...');
    try {
      execSync('node scripts/generateIcons.cjs', { cwd: root, stdio: 'inherit' });
    } catch (e) {
      console.warn(`  ⚠ Icon auto-generation failed: ${e.message}`);
      console.warn('  ⚠ Run: npm install sharp png-to-ico png2icons --save-dev && npm run icons');
    }
  }

  const needed = {
    win32:  ['icon.ico'],
    darwin: ['icon.icns', 'icon.png'],
    linux:  ['icon.png'],
  };

  // `platform` here is builder-util's Platform enum object ({ name, ... }),
  // e.g. Platform.WINDOWS.name === 'windows' — not the Node.js `win32` you'd
  // get from `process.platform`. Map electron-builder's platform names to the
  // ones this table already uses.
  const platformKey = { windows: 'win32', mac: 'darwin', linux: 'linux' }[platform?.name] || 'linux';
  const icons        = needed[platformKey] || needed.linux;

  for (const icon of icons) {
    const iconPath = path.join(assetsDir, icon);
    if (!existsSync(iconPath)) {
      console.warn(`  ⚠ ${icon} not found in assets/ — using placeholder`);
      // Create a minimal placeholder so the build doesn't fail
      // Replace with a real 512x512 icon before distributing
      generatePlaceholderIcon(iconPath, icon);
    } else {
      console.log(`  ✓ ${icon} found`);
    }
  }

  // ── Check NSIS include file ─────────────────────────────────────────────────
  const nsisPath = path.join(assetsDir, 'installer.nsh');
  if (!existsSync(nsisPath)) {
    writeFileSync(nsisPath, '; Custom NSIS installer script\n; Generated by Rāma AGI build system\n');
  }

  // ── Rebuild native modules ──────────────────────────────────────────────────
  console.log('\n  ⬢ Rebuilding native modules for Electron...');
  try {
    execSync('npx electron-rebuild --force', { cwd: root, stdio: 'inherit' });
    console.log('  ✓ Native modules rebuilt\n');
  } catch (err) {
    console.warn(`  ⚠ electron-rebuild failed: ${err.message}`);
    console.warn('  ⚠ argon2/node-pty may not work in packaged app');
    console.warn('  ⚠ Install Visual Studio Build Tools on Windows to fix this\n');
  }

  // Returning false tells electron-builder that native dependencies have been
  // handled here, so it does not run its own rebuild pass on top of the one
  // above. This is what the comment at the top of this file always described and
  // never actually did: without it, argon2 and node-pty can be compiled twice in
  // a single build, which on a machine with a real C++ toolchain is minutes of
  // duplicated work for an identical result.
  return false;
};

function generatePlaceholderIcon(iconPath, filename) {
  // Write a minimal valid file so build doesn't crash
  // For ICO: minimal 1x1 pixel ICO header
  // For PNG: minimal 1x1 PNG
  // For ICNS: placeholder text
  const ext = path.extname(filename).toLowerCase();
  if (ext === '.ico') {
    // Minimal 1x1 ICO file (binary)
    const ico = Buffer.from([
      0x00,0x00, // reserved
      0x01,0x00, // type: icon
      0x01,0x00, // count: 1
      0x01,0x01, // width=1, height=1
      0x00,      // color count
      0x00,      // reserved
      0x01,0x00, // planes
      0x18,0x00, // bit count: 24
      0x28,0x00,0x00,0x00, // size of image data
      0x16,0x00,0x00,0x00, // offset to image data
      // BITMAPINFOHEADER (40 bytes)
      0x28,0x00,0x00,0x00,
      0x01,0x00,0x00,0x00,
      0x02,0x00,0x00,0x00,
      0x01,0x00, 0x18,0x00,
      0x00,0x00,0x00,0x00,
      0x08,0x00,0x00,0x00,
      0x00,0x00,0x00,0x00,
      0x00,0x00,0x00,0x00,
      0x00,0x00,0x00,0x00,
      0x00,0x00,0x00,0x00,
      // pixel data: violet #7700ff
      0xff,0x00,0x77, 0xff,0x00,0x77,
      0x00,0x00, // AND mask row
    ]);
    require('fs').writeFileSync(iconPath, ico);
  } else if (ext === '.png') {
    // Minimal 1x1 violet PNG
    const png = Buffer.from([
      0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,
      0x00,0x00,0x00,0x0d,0x49,0x48,0x44,0x52,
      0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
      0x08,0x02,0x00,0x00,0x00,0x90,0x77,0x53,
      0xde,0x00,0x00,0x00,0x0c,0x49,0x44,0x41,
      0x54,0x08,0xd7,0x63,0xf8,0xcf,0xc0,0x00,
      0x00,0x00,0x02,0x00,0x01,0xe2,0x21,0xbc,
      0x33,0x00,0x00,0x00,0x00,0x49,0x45,0x4e,
      0x44,0xae,0x42,0x60,0x82,
    ]);
    require('fs').writeFileSync(iconPath, png);
  } else {
    require('fs').writeFileSync(iconPath, '# placeholder\n');
  }
  console.log(`  ⬢ Generated placeholder ${filename} (replace with real icon before distributing)`);
}
